### ISSUE TITLE
Don't report JSON (un)marshalling as RPC no data.

### ISSUE THREAD

**Issue by goral09** [caspercommunityio/casper-scala-sdk#10]
**Priority: HIGH**
**Files affected:** `HttpRPCService.scala`

In class `HttpRPCService`, the send method catches any errors thrown in post and JSON unmarshalling and maps them to `RPCError(code = 0)` which means `"No result returned by the RPC Call"`. This is incorrect and misleading: if code failed at JSON parsing it should be signaled as such.

**Comment by caspercommunityio** [comment]
new error code created
