### ISSUE TITLE
Side-effecting parameterless methods should have parentheses.

### ISSUE THREAD

**Issue by goral09** [caspercommunityio/casper-scala-sdk#2]
**Priority: LOW**

There are parameterless methods that are defined (and called) without parentheses. While having non-parenthesis accessory methods is fine, it's considered good style to include empty parentheses for side-effecting function.

Example of side-effecting but parameterless method is CasperSdk.getStatus  - it's performing a blocking call to node's RPC.

**Comment by caspercommunityio** [comment]
parenthesis added
